#ifndef RESPONSES_HPP
#define RESPONSES_HPP

enum Responses {
	RPL_WELCOME = 001,
	RPL_YOURHOST = 002,
	RPL_CREATED = 003,
	RPL_MYINFO = 004,
	RPL_USERHOST = 302,
	RPL_MOTDSTART = 375,
	RPL_MOTD = 372,
	RPL_ENDOFMOTD = 376
};

#endif /*RESPONSES_HPP*/
